### PR TITLE
Added GreenhopperDomain and associated Entities to support retrieving…

### PR DESCRIPTION
**Pull request by alfadormx**
Hi
I have added a new domain called GreenhopperDomain. This is used for fetching the SprintReport. As of today, this SprintReport API endpoint is nowhere documented but I managed to make and test Domain for it on your library.
I am using this domain and call in an internal project for my company. I would kindly appreciate if you accept this Pull Request so I no longer have to reference my version of you great API.
Kind Regards
Hector HERNANDEZ

### CODE REVIEW

**Comment by alfadormx** [comment]
Not sure why the AppVeyor build failed.
It seems there are some common errors running .NET Core projects on AppVeyor. 
@Lakritzator  Is this the reason why you have pushed some commits with the **[skip ci]** comment?

**Comment by Lakritzator** [comment]
Hi,
I will need to take a look at your changes, Greenhopper is no longer a product they migrated into Jira with the "title" Agile. And for Agile there is already a domain, so maybe this change should be in there.

Pull-Requests always fail, as the credentials for the tests are not decrypted (to prevent you from adding a Debug.WriteLine or similar with the username and password) so the tests fail.

Best wishes,
Robin

**Comment by Lakritzator** [comment]
See here: https://www.atlassian.com/blog/archives/renaming-greenhopper-and-bonfire
That was in 2013... so if this API is a remained of that, it might be something I cannot maintain, as it's not supported.

Anyway, I didn't check your changes yet.

**Comment by Lakritzator** [comment]
Seems to be related to https://jira.atlassian.com/browse/JSWSERVER-12877

**Comment by alfadormx** [comment]
Could there be a way to tag some endpoints like the Greenhopper Domain ones into a sort of 'Not Mantained' but keep then anyways? These endpoins are used everywhere the reports and charts are used and they provide essential information. I tried to retrieve the same information using the normal API endpoints and it turned nearly impossible to achieve without requesting every worklog and history per item.

**Comment by Lakritzator** [comment]
I think it's okay to add them, I will place a note on it... I just can't support this when there are any errors, which I will add to the note. That is also a good reason to keep the API in the Greenhopper domain 👍 

At least you did a good job with the pull-request, looks very clean.

Can you tell me what you do with the results of the call? How do you process them further?

P.S.
I will remove the tests from the build when there is a pull request, there is no reason for it when they fail anyway.

**Comment by alfadormx** [comment]
Thanks for accepting the Pull Request! I use the Jira Reports in a small tool I use where I fetch all the reports for the latest sprints of every team. With those reports I generate and calculate some KPIs like the number of stories present at the beginning of the sprint vs the number of sprints completed, the number of bugs at the end of the sprint, the velocity of every team based only on stories completed (not every other element that has points in it) and so on.

**Comment by alfadormx** [comment]
Now I'll wait for the Nuget package to contain my changes to update my reference to the latest version of it on my code.

**Comment by Lakritzator** [comment]
How do you present these KPIs?

Actually ReportIssue could use some documentation, my build log is full with "missing comments"... 😒 

Anyway, I had some weird build errors, seems a lot of the tools I use were changed since April where the last build was made. But new versions are now published, Dapplo.Jira 0.6.39 should be a clean build.
I will update the documentation later, as I am actually on holidays, this currently is still done by hand.

The build was still based on xproj / project.json and this causes some issues. I will update the project to VS2017, as this is the only way forward...

**Comment by Lakritzator** [comment]
I have found a copy/paste error:

Was:
```
        [JsonProperty(PropertyName = "tatFieldValue")]
        public ValueField StatFieldValue { get; set; }
```
Should have been:
```
        /// <summary>
        ///     The Statistic Field value
        /// </summary>
        [JsonProperty(PropertyName = "statFieldValue")]
        public ValueField StatFieldValue { get; set; }
```
I also removed the following properties from the ReportIssue:

```
        public string StatusId { get; set; }
        public string StatusName { get; set; }
        public Uri StatusUrl { get; set; }
```
As all the information is already in the property Status, so if you were using those values you will need to use the Status property, which a Name, IconUri and Id

I also added the missing comments, so the documentation makes more sense.

**Comment by alfadormx** [comment]
Hi, thanks for updating the documentation and fixing those issues, my bad!
I did see that the Status object and the status property outside of it were redundant but that is the way the response is sent.
I found a small issue on the SprintInReport object. The RemoteLinks property is in fact an object and not just a list of strings. I will fix it right away.
To anwer your question, for the moment I just generate a csv for every agile team. I am implementing this tool to be configurable in a sense where you specify the boards you are interested in and a starting date. From there, the tool runs by finding the board, the sprints and then requests the reports to generate a CSV for every team. From then on my process is manual, I update some tables in confluence and add a tendency graph. 
I don't know yet if I will use your Dapplo.Confluence Library to do this automatically OR actually somehow create a page that I would call from an Iframe and put it as a Confluence/Jira plugin and display those KPIs directly as any other widget would do.

**Comment by Lakritzator** [comment]
It would be cool if you can use Dapplo.Confluence, but you might find some issues with it... Probably nothing we cannot solve, still.

The hardest part is the testing, as there are no real unit tests but more integration tests, this is very tricky.

Both projects were made for Greenshot, and actually just to get a list of jiras and attach a screenshot, or upload a screenshot to an existing page... but than it grew a bit further 😄 

P.S.
If you want to generate a graph, have a look at [LiveCharts](https://lvcharts.net/)

**Comment by alfadormx** [comment]
Thanks for the tip. I will take a look at both LiveCharts and Dapplo.Confluence :)

**Pull request merged**
