### PR TITLE
Cookie-based authentication  && several fixes

### PR DESCRIPTION
**Pull request by rualert**
Could you please pull it and update nuget package

### CODE REVIEW

**Comment by Lakritzator** [comment]
Don't mind the build error, didn't expect any PR's yet so I need to skip calling a tool when this is the case.

That's pretty cool, although there is a bug in the StartSessionAsync with the _behaviour handling.. you are overwriting the default OnHttpRequestMessageCreated action and setting it to null afterwards which will probably not be good. That's not really your fault, more mine due to the missing documentation of my HttpExtensions framework.

I will need to check what is the best fix, there are a couple of ways:

1. Simplest: Post a StringContent object where you set the ContentType yourself. (yes this works, just post an instance of a class which extends HttpContent, like StringContent, and it will be uploaded as if you are using HttpClient yourself)
2. as elsewhere: Create a credentials object to post, the "application/json" will be set automatically as it's recognised as json.
3. Create a new behaviour for this logic by cloning the other, and wrapping the OnHttpRequestMessageCreated.. way to complicated.

Oh I did notice a small bug in my Http framework:
A cookie container is already created if UseCookies in the HttpSettings (global or in your HttpBehaviour) is true, I should actually add the container to the HttpBehaviour so it's correctly passed to the client handler.  This way you would only have to add the cookie in the StartSessionAsync and remove it in the EndSessionAsync.

I will merge / fix / test  this for you, if that is okay with you?

P.S.
I would really love to hear about where and for what you use this.
Do you use .NET Core?? I still want to update it to use the NET Platform Standard..

**Comment by rualert** [comment]
Resolution with StringContent works fine. Looks more accurat. I like it.
```
 var content = new StringContent($"{{ \"username\": \"{login}\", \"password\": \"{password}\"}}");
 content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");

 var response = await sessionUri.PostAsync<HttpResponse<SessionResponseSuccess, Error>>(content, cancellationToken);
```

> I will merge / fix / test this for you, if that is okay with you?

Yes, please.
> I would really love to hear about where and for what you use this.

Nothing special, just my work.

> Do you use .NET Core??

I use it only for my home projects.

**Comment by Lakritzator** [comment]
Yes, the string-content is the simplest way :smile: 

I already added the CookieContainer logic to the HttpExtensions, but the build doesn't work.

There are some difficulties with Chocolatey:
> The site is currently experiencing heavy load. We are upgrading our infrastructure. Expect intermittent issues and degraded performance.

And Chocolatey is used on the CI-Builder to get GitLink which enhances the pdb files with Github references) so it might take me a bit longer...

**Comment by Lakritzator** [comment]
So, I have made the modifications and added a test for the session... if Chocolatey doesn't complain my CI server should be building & publishing it in < 30 minutes. (currently there is rush hour, it's slow)

Does the sentence "Please be aware that although cookie-based authentication has many benefits, such as performance (not having to make multiple authentication calls)"
Have an ending?? "although" assumes that something should follow :smile: 
And now you made me curious, what the the disadvantage of using the session?

P.S.
Oh, if speed is an important factor for your current implementation: I am currently working on a simple async cache implementation, which you can configure to retrieve e.g. avatars or other information, the information **can** expire (depending on the configuration) and will again be retrieved when it's requested.

Here is an example:

	public class AvatarCache : AsyncMemoryCache<AvatarUrls, BitmapSource>
	{
		private readonly JiraApi _jiraApi;

		public AvatarCache(JiraApi jiraApi)
		{
			_jiraApi = jiraApi;
		}

		public AvatarSizes AvatarSize { get; set; } = AvatarSizes.ExtraLarge;

		protected override string CreateKey(AvatarUrls keyObject)
		{
			return keyObject.GetUri(AvatarSize).AbsoluteUri;
		}

		protected override async Task<BitmapSource> CreateAsync(AvatarUrls key, CancellationToken cancellationToken = new CancellationToken())
		{
			return await _jiraApi.GetAvatarAsync<BitmapSource>(key, AvatarSize, cancellationToken);
		}
	}


Get the BitmapSource (WPF)

	var avatarCache = new AvatarCache(jiraApi);
	var me = await _jiraApi.WhoAmIAsync();
	var avatar = await _avatarCache.GetOrCreateAsync(me.Avatars);

I just pushed the code, there is a small change in the AvatarUrls as I added GetUri, but I am not releasing as it's just a minor change.

**Comment by rualert** [comment]
Thanks.
> Have an ending?? "although" assumes that something should follow 

Oh yes. :) With the session key is not so simple. Cookies can expire over time, which leads to confusion. In our case, it's not a problem.

**Comment by rualert** [comment]
All my changes in the main branch. What these cases have to do with my fork? I have no idea.

**Comment by Lakritzator** [comment]
I was just assuming you made the Pull-Request for speed reasons, and that is why I wanted to let you know about the cache. I thought that you **might** be interested into having a one to speed up some operations.

**Comment by rualert** [comment]
Actually, I had very not understand how these forks work. As I understand it in my version no recent changes. If so, before change anything, I'll need the latest code. Then I'll have to do fork again. This fork no longer needed.

**Comment by Lakritzator** [comment]
Ah yes, now I know what you mean.
You either manually (commandline or whatever tool you haven) pull in my changes or just throw away the fork and create a new one when needed. I actually don't like that much either, it should be possible to auto sync.. but anyway.

Again, thanks for the pull request!

**Pull request merged**
