### PR TITLE
Mdsnippets stuff

### PR DESCRIPTION
**Pull request by SimonCropp**
* re-use readme
 * make docs re-gen on commit
 * remove redundant csproj stuff

### CODE REVIEW

**Comment by Lakritzator** [comment]
I had some stress at work and home, sorry I haven't had much time to look at it in details yet.
It looks like you really put a lot of effort in it ❤️ 

Some questions I had:
1. why would one use an ID like 2cc28931?
2. Any reason why you removed the github sponsor link?
3. I guess with the  you mean I should include the readme.md or is this done? Btw. the documentation still is incomplete, as I'm looking at the best way to get this working. And I want to roll it out over all the other projects.

I will now first take a look at Github actions, didn't invest time to it yet.

**Comment by SimonCropp** [comment]
> why would one use an ID like 2cc28931?

usually sharing a deep link on social media r issues. in an earlier version the anchor was the snippet name, but given many people use long snippet names it was producing more html and impacting the signal to noise ratio. TBH i am considering making it an option to either use the snippet name or the hash in a future version

> Any reason why you removed the github sponsor link?

that was unintentional. i will put it back

**Comment by SimonCropp** [comment]
> Any reason why you removed the github sponsor link

ok i see. i made the `doc/index.md` be in sync with the `readme.md` . and the readme had paypal

**Comment by Lakritzator** [comment]
It's not a big deal, I gladly put it back, I was just wondering why 🤷‍♂️ 
Maybe you had a bigger motivation than I could think of.

**Comment by SimonCropp** [comment]
actually i will make the snippets non hashed by default and have an opt in option. so hold off merging this for a bit

**Comment by Lakritzator** [comment]
No hurries!!! I've been under stress a lot lately...

**Comment by SimonCropp** [comment]
> I've been under stress a lot lately

anything i can help with?

**Comment by Lakritzator** [comment]
No, but thanks for asking. 🤗 

It's just at work. Last year I took a new position as a software architect in the same company I already worked for. I used to work as a developer / technical lead for the CTI (computer telephone integration) solution, and at the same time I moved my colleague who was my "backup" also moved jobs. Just much farther away, so I got stuck with all the old work. This has been following me since, whereas in my new job I have enough work for 3 people... so that would technically be 4 jobs...

Combine that with a 4yo "strong emotionally boy" in covid times where we don't have the luxury that he can always go to the kindergarten... it's just sucking the energy away 🤷‍♂️ 

Personally I can't motivate myself much, as my dev system from 2017 is **very** sluggish (8GB slow SSD). I've been waiting for a new laptop, but can't order what I want (Lenovo Legion with Ryzen 4800H & RTX 2060) as it hasn't been available yet although it was promised mid-2020. Alternatives (Intel) costs me more than I am willing to spend.

**Pull request merged**
